{{- if .Values.secrets.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "vulntracker.fullname" . }}-external
  labels:
    {{- include "vulntracker.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secrets.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.secrets.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.secrets.secretName }}
    creationPolicy: Owner
  data:
    {{- range .Values.secrets.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
    {{- end }}
{{- end }}
