{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vulntracker.serviceAccountName" . }}
  labels:
    {{- include "vulntracker.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
